[build]
base = "frontend-web"
publish = "dist"
command = "npm run build"

[build.environment]
VITE_API_URL = "https://api.dataxiom.it"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
"Cache-Control" = "max-age=0,no-cache,no-store,must-revalidate"

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "max-age=31536000,immutable"
