#!/bin/bash

# ============================================================================
# Badge System — Production .env Generator
# ============================================================================
# This script generates secure JWT secrets and creates a production .env template.
#
# Usage:
#   bash scripts/generate-prod-env.sh
#
# Output:
#   - Generates two 32-char random JWT secrets
#   - Creates .env.production template
#   - Displays credentials for manual entry
# ============================================================================

set -e

echo "=========================================="
echo "🔐 Badge System Production .env Generator"
echo "=========================================="
echo ""

# Generate random secrets (32 chars, base64)
JWT_SECRET=$(openssl rand -base64 32)
JWT_REFRESH_SECRET=$(openssl rand -base64 32)

echo "✅ Generated JWT Secrets:"
echo ""
echo "JWT_SECRET:"
echo "$JWT_SECRET"
echo ""
echo "JWT_REFRESH_SECRET:"
echo "$JWT_REFRESH_SECRET"
echo ""

# Create .env.production template
cat > .env.production << 'EOF'
# ============================================================================
# Badge System — Production Environment Configuration
# ============================================================================
# CRITICAL: Keep this file secure. Store in AWS Secrets Manager or EC2 private location.
# Never commit this file to git.
# ============================================================================

# Server
NODE_ENV=production
PORT=3000
LOG_LEVEL=info
APP_NAME=Badge System API

# Database (AWS RDS PostgreSQL)
# Format: postgresql://user:password@hostname:port/dbname
DATABASE_URL=postgresql://postgres:PASSWORD_HERE@badge-system-db.cvs80y0my080.eu-west-1.rds.amazonaws.com:5432/badge_system
DB_HOST=badge-system-db.cvs80y0my080.eu-west-1.rds.amazonaws.com
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=PASSWORD_HERE
DB_NAME=badge_system
DB_POOL_MIN=5
DB_POOL_MAX=20

# Auth0
AUTH0_DOMAIN=YOUR_AUTH0_DOMAIN.auth0.com
AUTH0_CLIENT_ID=YOUR_AUTH0_CLIENT_ID
AUTH0_CLIENT_SECRET=YOUR_AUTH0_CLIENT_SECRET
AUTH0_AUDIENCE=https://api.badge.dataxiom.it

# JWT Tokens (Generated by generate-prod-env.sh)
JWT_SECRET=REPLACE_WITH_JWT_SECRET_FROM_ABOVE
JWT_EXPIRY=30m
JWT_REFRESH_SECRET=REPLACE_WITH_JWT_REFRESH_SECRET_FROM_ABOVE
JWT_REFRESH_EXPIRY=7d

# CORS & Security
CORS_ORIGIN=https://api.badge.dataxiom.it,https://dashboard.badge.dataxiom.it
CORS_CREDENTIALS=true
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=100

# Redis Caching (Optional but recommended)
REDIS_URL=redis://localhost:6379
CACHE_ENABLED=true
CACHE_TTL=300

# Monitoring (Optional)
SENTRY_DSN=
SENTRY_ENVIRONMENT=production

# AWS Region
AWS_REGION=eu-west-1

# Feature Flags
ENABLE_OFFLINE_MODE=false
ENABLE_PAYROLL_API=false
ENABLE_WEBHOOKS=false

# Security (Production values)
DISABLE_AUTH=false
SEED_TEST_DATA=false
MOCK_AUTH0=false
EOF

echo "=========================================="
echo "📝 Next Steps:"
echo "=========================================="
echo ""
echo "1. Review .env.production (just created)"
echo ""
echo "2. Get credentials from AWS Console:"
echo "   - RDS Password: AWS Console → RDS → Databases → badge-system-db"
echo "   - EC2 Public IP: AWS Console → EC2 → Instances → badge-system-api"
echo ""
echo "3. Get credentials from Auth0:"
echo "   - Dashboard → Applications → Badge System API"
echo "   - Copy: Domain, Client ID, Client Secret"
echo ""
echo "4. Edit .env.production and replace:"
echo "   - PASSWORD_HERE (RDS password)"
echo "   - YOUR_AUTH0_DOMAIN (from Auth0)"
echo "   - YOUR_AUTH0_CLIENT_ID (from Auth0)"
echo "   - YOUR_AUTH0_CLIENT_SECRET (from Auth0)"
echo "   - REPLACE_WITH_JWT_SECRET_FROM_ABOVE (copy from above)"
echo "   - REPLACE_WITH_JWT_REFRESH_SECRET_FROM_ABOVE (copy from above)"
echo ""
echo "5. Copy to EC2:"
echo "   scp -i ~/.ssh/badge-key.pem .env.production ubuntu@EC2_IP:/home/ubuntu/badge-api/.env"
echo ""
echo "=========================================="
echo ""
